
# spring config
spring:
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  # Datasource config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        allow: ""
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
          enabled: true
        log4j:
          enabled: true
          result-set-log-enabled: false
          statement-log-enabled: false
          connection-log-enabled: true
        wall:
          config:
            multi-statement-allow: true
    dynamic:
      datasource:
        #数据源
        base:
          url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/spbi?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: ${MYSQL_USER:root}
          password: ${MYSQL_PWD:123456}
      primary: base

  redis:
    # Redis数据库索引（默认为 0）
    database: 1
    # Redis服务器地址
    host: ${REDIS_HOST:localhost}
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000
# enable underscore to camel case
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  # MySQL、MariaDB、Oracle、SQL Server config
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# logging config
logging:
  level:
    root: info
    cn.tsit.spbi.mapper: debug

diboot:
  iam:
#    /swagger**/**,/webjars/**,/v3/**,/doc:
#      html:
    anon-urls: /**
    enable-permission-check: false
    token-expires-minutes: 60


  # Diboot Devtools 配置参数
  devtools:
    codes-author: tsit
    codes-copyright: tsit
    codes-version: 1.0
    output-path: spbi-plat/src/main/java/cn/tsit/spbi/
    output-path-sql: spbi-plat/src/main/resources/sql
    enable-lombok: true
    enable-swagger: true
    generate-mapper-xml: true
